#########
##  ============LICENSE_START====================================================
##  org.onap.aaf
##  ===========================================================================
##  Copyright (c) 2017 AT&T Intellectual Property. All rights reserved.
##  ===========================================================================
##  Licensed under the Apache License, Version 2.0 (the "License");
##  you may not use this file except in compliance with the License.
##  You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##  Unless required by applicable law or agreed to in writing, software
##  distributed under the License is distributed on an "AS IS" BASIS,
##  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##  See the License for the specific language governing permissions and
##  limitations under the License.
##  ============LICENSE_END====================================================
##
#
# Default values for aaf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  persistence:
    enabled: true

services:
  aaf_env: "DEV"
  aaf_id: "aaf@aaf.osaaf.org"
  public_fqdn: "aaf.osaaf.org"
  aaf_locator_name: "%NS.%N"
  aaf_locator_name_helm: "%CNS.%NS.%N"
  cadi_latitude: "38.0"  
  cadi_longitude: "-72.0"  
  cass:
    replicas: 1
    fqdn: "aaf-cass"
    cluster_name: "osaaf"
    heap_new_size: "512M"
    max_heap_size: "1024M"
    storage_port: 7000
    ssl_storage_port: 7001
    native_trans_port: 9042
    rpc_port: 9160
    dc: "dc1"
  service:
    replicas: 1
    fqdn: "aaf-service"
    internal_port: 8100
    public_port: 30080
  locate:
    replicas: 1
    fqdn: "aaf-locate"
    internal_port: 8095
    public_port: 30081
  oauth:
    replicas: 1
    fqdn: "aaf-oauth"
    internal_port: 8140
    public_port: 30082
  cm:
    replicas: 1
    fqdn: "aaf-cm"
    internal_port: 8150
    public_port: 30084
  gui:
    replicas: 1
    fqdn: "aaf-gui"
    internal_port: 8200
    public_port: 30083
  fs:
    replicas: 1
    fqdn: "aaf-fs"
    internal_port: 8096
    public_port: 30085
    
persistence:
  # Note: Minikube will persist to /data on your host machine
  mountPath: "/data/aaf"
  cass:
    volumeReclaimPolicy: Retain
    accessMode: ReadWriteOnce
    size: 10Gi
    mountSubPath: "cass"
    storageClass: "manual"
  status:
    volumeReclaimPolicy: Delete
    accessMode: ReadWriteOnce
    size: 10M
    mountSubPath: "status"
    storageClass: "manual"
  config:
    volumeReclaimPolicy: Retain
    accessMode: ReadWriteOnce
    size: 2Gi
    mountSubPath: "config"
    storageClass: "manual"

image:
  # When using locally built Docker Container, set Repository to ""
  repository: ""
  # When using Docker Repo, add, and include trailing "/"
  # repository: nexus3.onap.org:10003/
  # repository: localhost:5000/
  version: 2.1.16-SNAPSHOT

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
