#########
##  ============LICENSE_START====================================================
##  org.onap.aaf
##  ===========================================================================
##  Copyright (c) 2017 AT&T Intellectual Property. All rights reserved.
##  ===========================================================================
##  Licensed under the Apache License, Version 2.0 (the "License");
##  you may not use this file except in compliance with the License.
##  You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##  Unless required by applicable law or agreed to in writing, software
##  distributed under the License is distributed on an "AS IS" BASIS,
##  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##  See the License for the specific language governing permissions and
##  limitations under the License.
##  ============LICENSE_END====================================================
##
###
### AAF-OAUTH
###
kind: Service
apiVersion: v1
metadata:
  name: aaf-oauth
spec:
  selector:
    app: aaf-oauth
  type: NodePort
  ports:
    - name: {{.Values.services.oauth.fqdn}}
      protocol: TCP
      port: {{.Values.services.oauth.internal_port}}
      nodePort: {{.Values.services.oauth.public_port}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aaf-oauth
  labels:
    app: aaf-oauth
spec:
  replicas: {{ .Values.services.oauth.replicas }}
  selector:
    matchLabels:
      app: aaf-oauth
  template:
    metadata:
      labels:
        app: aaf-oauth
    spec:
      volumes:
        # Use this Pod Sharing dir to declare various States of starting
      - name: aaf-config-vol
        persistentVolumeClaim:
          claimName: aaf-config-pvc
      - name: aaf-status-vol
        persistentVolumeClaim:
          claimName: aaf-status-pvc
      initContainers:
        - name: aaf-config-container
          image: {{ .Values.image.repository }}onap/aaf/aaf_config:{{ .Values.image.version }}
          imagePullPolicy: IfNotPresent
          command: ["bash","/opt/app/aaf_config/bin/agent.sh"]
          volumeMounts:
            - mountPath: "/opt/app/osaaf"
              name: aaf-config-vol
          env:
            - name: AAF_ENV
              value: "{{ .Values.services.aaf_env }}"
            - name: LATITUDE
              value: "{{ .Values.services.cadi_latitude }}"
            - name: LONGITUDE
              value: "{{ .Values.services.cadi_longitude }}"
            - name: aaf_locator_container
              value: "helm"
            - name: aaf_locator_container_ns
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: aaf_locate_url
              value: "https://aaf-locate.{{.Release.Namespace }}:{{.Values.services.locate.internal_port}}"
            - name: aaf_locator_public_fqdn
              value: "{{.Values.services.public_fqdn}}"
            - name: aaf_locator_name
              value: "{{.Values.services.aaf_locator_name}}"
            - name: aaf_locator_name_helm
              value: "{{.Values.services.aaf_locator_name_helm}}"
            - name: CASSANDRA_CLUSTER
              value: "{{.Values.services.cass.fqdn}}.{{.Values.services.ns}}"
#            - name: CASSANDRA_USER
#              value: ""
#            - name: CASSANDRA_PASSWORD
#              value: ""
#           - name: CASSANDRA_PORT
#              value: ""
      containers:
###
### AAF-OAUTH
###
      - name: aaf-oauth
        image: {{ .Values.image.repository }}onap/aaf/aaf_oauth:{{ .Values.image.version }}
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash","-c","cd /opt/app/aaf && /bin/bash bin/pod_wait.sh aaf-oauth nc aaf-cass.{{ .Release.Namespace }} {{ .Values.services.cass.native_trans_port }} aaf-service && exec bin/oauth"]
        volumeMounts:
        - mountPath: "/opt/app/osaaf"
          name: aaf-config-vol
        - mountPath: "/opt/app/aaf/status"
          name: aaf-status-vol
        ports:
        - name: {{.Values.services.oauth.fqdn}}
          protocol: TCP
          containerPort: {{.Values.services.oauth.internal_port}}
        env:
        - name: aaf_locator_ns
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
