#########
##  ============LICENSE_START====================================================
##  org.onap.aaf
##  ===========================================================================
##  Copyright (c) 2017 AT&T Intellectual Property. All rights reserved.
##  ===========================================================================
##  Licensed under the Apache License, Version 2.0 (the "License");
##  you may not use this file except in compliance with the License.
##  You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##  Unless required by applicable law or agreed to in writing, software
##  distributed under the License is distributed on an "AS IS" BASIS,
##  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##  See the License for the specific language governing permissions and
##  limitations under the License.
##  ============LICENSE_END====================================================
##
###
### AAF-SERVICE
###
kind: Service
apiVersion: v1
metadata:
  name: aaf-service
spec:
  type: NodePort
  selector:
    app: aaf-service
  ports:
    - name: {{.Values.services.service.fqdn}}
      protocol: TCP
      nodePort: {{.Values.services.service.public_port}}
      port: {{.Values.services.service.internal_port}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aaf-service
  labels:
    app: aaf-service
spec:
  replicas: {{ .Values.services.service.replicas }}
  selector:
    matchLabels:
      app: aaf-service
  template:
    metadata:
      labels:
        app: aaf-service
    spec:
      volumes:
      - name: aaf-config-vol
        persistentVolumeClaim:
          claimName: aaf-config-pvc
      - name: aaf-status-vol
        persistentVolumeClaim:
          claimName: aaf-status-pvc
      initContainers:
        - command:
            - /bin/sh
            - -c
            - |
              chmod -R 775 /opt/app/aaf/status
              chown -R 1000:1000 /opt/app/aaf/status
              chmod -R 775 /opt/app/osaaf
              chown -R 1000:1000 /opt/app/osaaf
          image: busybox:1.28
          imagePullPolicy: {{ .Values.global.pullPolicy | default .Values.pullPolicy }}
          name: init-sysctl
          volumeMounts:
          - mountPath: /opt/app/aaf/status
            name: aaf-status-vol
          - mountPath: /opt/app/osaaf
            name: aaf-config-vol
        - name: aaf-config-container
          image: {{ .Values.image.repository }}onap/aaf/aaf_config:{{ .Values.image.version }}
          imagePullPolicy: IfNotPresent
          command: ["bash","/opt/app/aaf_config/bin/agent.sh"]
          volumeMounts:
            - mountPath: "/opt/app/osaaf"
              name: aaf-config-vol
            - mountPath: "/opt/app/aaf/status"
              name: aaf-status-vol
          env:
            - name: aaf_env
              value: "{{ .Values.services.aaf_env }}"
            - name: aaf_id
              value: "{{ .Values.services.aaf_id }}"
            - name: aaf_locate_url
              value: "https://aaf-locate.{{.Release.Namespace }}:{{.Values.services.locate.internal_port}}"
            - name: aaf_locator_container
              value: "helm"
            - name: aaf_locator_container_ns
              value: "{{ .Release.Namespace }}"
            - name: aaf_locator_fqdn
              value: "{{.Values.services.fqdn}}"
            - name: aaf_locator_public_fqdn
              value: "{{.Values.services.public_fqdn}}"
            - name: cadi_latitude
              value: "{{ .Values.services.cadi_latitude }}"
            - name: cadi_longitude
              value: "{{ .Values.services.cadi_longitude }}"
            - name: cm_always_ignore_ips
              value: "true"
            - name: CASSANDRA_CLUSTER
              value: "{{.Values.services.cass.fqdn}}.{{.Release.Namespace }}"
#            - name: CASSANDRA_USER
#              value: ""
#            - name: CASSANDRA_PASSWORD
#              value: ""
#           - name: CASSANDRA_PORT
#              value: ""
###
### AAF-SERVICE
###
      containers:
      - name: aaf-service
        image: {{ .Values.image.repository }}onap/aaf/aaf_core:{{ .Values.image.version }}
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash","-c","cd /opt/app/aaf && /bin/bash bin/pod_wait.sh aaf-service nc aaf-cass.{{ .Release.Namespace }} {{ .Values.services.cass.native_trans_port }} aaf-cass && exec bin/service"]
        volumeMounts:
        -  mountPath: "/opt/app/osaaf"
           name: aaf-config-vol
        -  mountPath: "/opt/app/aaf/status"
           name: aaf-status-vol
        ports:
        - name: service
          protocol: TCP
          containerPort: {{.Values.services.service.internal_port}}

